export const PRODUCTS = [
  {
    id: 0,
    name: 'Sayuri Junmai Nigori',
    brand: 'Hakutsuru',
    type: 'plum',
    style: 'semi-sweet',
    taste: 'floral, cream, smooth',
    body: 'light',
    description:
      'Japan - Sayuri means ""little lily"" a perfect description for this soft floral-noted Nigori. This unfiltered sake has a very light nose filled with lush cream, cherry blossom, and light fruit. Semi-sweet palate with a very smooth finish.',
    image: '/assets/products/sayuri.png',
    price: '$11',
  },
  {
    id: 1,
    name: 'Superior Junmai Ginjo',
    brand: 'Hakutsuru',
    type: 'sake',
    style: 'semi-sweet',
    taste: 'floral, crisp',
    body: 'light',
    description: '',
    image: '/assets/products/hakutsuru.png',
    price: '$12.59',
  },
  {
    id: 2,
    name: 'Gekkeikan Sake',
    brand: 'Gekkeikan',
    type: 'sake',
    style: 'semi-sweet',
    taste: 'dry, crisp',
    body: 'light',
    description: '',
    image: '/assets/products/gekkeikan.png',
    price: '$7.49',
  },
  {
    id: 3,
    name: 'Black & Gold',
    brand: 'Gekkeikan',
    type: 'sake',
    style: 'semi-sweet',
    taste: 'dry, crisp',
    body: 'light',
    description:
      'A blend of two sakes. Hints of honeydew, papaya, anise and roasted nuts, full-bodied with a long, smooth finish.',
    image: '/assets/products/blackgold.png',
    price: '$7.49',
  },
  {
    id: 4,
    name: 'Mio Sparkling Sake',
    brand: 'Sho Chiku Bai',
    type: 'sake',
    style: 'semi-sweet',
    taste: 'Fruity, Sweet, Smooth',
    body: 'light',
    description:
      'Japan - Delicate & refreshingly sweet with flavors of honeydew, lemongrass & peaches. Great with spicy or sweet fare - rolls made with hot peppers or chile oils, or those with fruit - a great finisher - refreshing - not too sweet!',
    image: '/assets/products/mio.png',
    price: '$10.99',
  },
  {
    id: 5,
    name: 'Horin Sake',
    brand: 'Gekkeikan',
    type: 'sake',
    style: 'semi-sweet',
    taste: 'Fruity, Clean',
    body: 'light',
    description:
      'Small batch microbrew, limited production. Slowly fermented at low temperatures for a more refined flavor. Mild, fruity aroma, hints of cantaloupe and honeysuckle, and a long, clean finish.',
    image: '/assets/products/horin.png',
    price: '$38.99',
  },

  {
    id: 6,
    name: 'Rock Sake Cloud',
    brand: 'Gekkeikan',
    type: 'sake',
    style: 'semi-sweet',
    taste: 'Clean, Fresh, Sweet',
    body: 'light',
    description:
      'California - Distilled from California rice with no additional alcohol, or preservatives added during the brewing process. Rough filtered for an opaque appearance and sweeter flavor. Aroma is clean and fresh, slightly sweet, with hints of melon and coconut and a delicate finish.',
    image: '/assets/products/rocksake.png',
    price: '$24.49',
  },
  {
    id: 7,
    name: 'Plum',
    brand: 'Gekkeikan',
    type: 'plum',
    style: 'Sweet',
    taste: 'Clean, Fresh, Sweet',
    body: 'full',
    description:
      'Made exclusively from Ume plums. Fermented and aged for 3 years. Hints of apple and pear. Rich and full-bodied with a long, smooth finish.',
    image: '/assets/products/plum_gekkeikan.png',
    price: '$12.99',
  },
  {
    id: 7,
    name: 'Sho Un',
    brand: 'Hakutsuru',
    type: 'sake',
    style: 'Dry',
    taste: 'White Peach, Apple, Pear',
    body: 'full',
    description:
      'Japan - SHO-UNE, meaning ""soaring clouds"", is a very well balanced, high quality Sake. The nose is filled with peach and apple aromas. The palate has a delicate texture and hints of pear flavor. Deeply complex, yet smooth, absolutely phenomenal!',
    image: '/assets/products/shoun.png',
    price: '$12.99',
  },
  {
    id: 8,
    name: 'Hanagoi Umeshu Plum Wine',
    brand: 'Hanagoi',
    type: 'plum',
    style: 'Semi-sweet',
    taste: 'Plum, Citrus, Smooth',
    body: 'Medium',
    description:
      'Akashi City, Japan - Umeshu is a plum infused Sake. Slightly sweeter flavor making for a perfect apertif or digestif. Serve chilled, over ice or even with soda water. Commonly used as a substitute for liquors, such as sweet vermouth. SULFITE FREE - GLUTEN FREE - 100% VEGAN',
    image: '/assets/products/hanagoiplum.png',
    price: '$22.99',
  },
]